services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes: 
      - ./cache:/data
  producer:
    build: ./producer
    volumes:
      - ./producer/src:/usr/src/app/src
    environment:
      - RATE=100
      - DURATION=1
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  consumer0:
    build: ./consumer
    image: consumer
    volumes:
      - ./consumer/src:/usr/src/app/src
    environment:
      - POD_NUMBER=0
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
  consumer1:
    image: consumer
    volumes:
      - ./consumer/src:/usr/src/app/src
    environment:
      - POD_NUMBER=1
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - consumer0